# Generated by Django 4.2 on 2023-05-07 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название банка')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('bank_name_eng', models.CharField(max_length=255, verbose_name='Название банка')),
                ('payment_system', models.CharField(max_length=255, verbose_name='Платежная система')),
                ('card_category', models.CharField(max_length=255, verbose_name='ПКатегория карт')),
                ('card_name', models.CharField(max_length=255, verbose_name='Имя карты')),
                ('card_quality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество карт')),
                ('chip_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название чипа')),
                ('chip_full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное название чипа')),
                ('chip_color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет чипа')),
                ('plastic_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип пластика')),
                ('plastic_color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет пластика')),
                ('magstripe_color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет магнитной полосы')),
                ('put_date', models.DateTimeField(auto_now=True)),
                ('in_archive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('payment_system', models.CharField(max_length=255, verbose_name='Платежная система')),
                ('card_category', models.CharField(max_length=255, verbose_name='ПКатегория карт')),
                ('card_name', models.CharField(max_length=255, verbose_name='Имя карты')),
                ('card_quality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество карт')),
                ('chip_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название чипа')),
                ('chip_full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное название чипа')),
                ('chip_color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет чипа')),
                ('plastic_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип пластика')),
                ('plastic_color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет пластика')),
                ('magstripe_color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет магнитной полосы')),
                ('put_date', models.DateTimeField(auto_now=True)),
                ('in_archive', models.BooleanField(default=False)),
                ('bank_name_eng', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.bankname')),
            ],
        ),
    ]
