# Generated by Django 4.2 on 2023-05-17 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_alter_projectline_bank_name_eng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('short_name', models.CharField(max_length=255, verbose_name='Платежная система')),
                ('name_eng', models.CharField(max_length=255, verbose_name='Платежная система')),
                ('name_rus', models.CharField(max_length=255, verbose_name='Платежная система')),
            ],
        ),
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Платежная система')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Платежная система')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('name_eng', models.CharField(max_length=255, verbose_name='Платежная система')),
                ('name_rus', models.CharField(max_length=255, verbose_name='Платежная система')),
                ('full_name_eng', models.CharField(max_length=255, verbose_name='Платежная система')),
                ('full_name_rus', models.CharField(max_length=255, verbose_name='Платежная система')),
                ('address_eng', models.CharField(max_length=255, verbose_name='Платежная система')),
                ('address_rus', models.CharField(max_length=255, verbose_name='Платежная система')),
                ('tolerance', models.IntegerField(null=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.countries')),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.hosts')),
                ('processing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.processing')),
            ],
        ),
        migrations.CreateModel(
            name='BankEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Платежная система')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255, verbose_name='Платежная система')),
                ('other', models.CharField(max_length=255, verbose_name='Платежная система')),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.banks')),
            ],
        ),
    ]
