# Generated by Django 4.2 on 2023-05-19 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_countries_processing_hosts_banks_bankemployees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Datasheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.CharField(max_length=255)),
                ('kcv_test', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='bankemployees',
            old_name='bank_id',
            new_name='bank',
        ),
        migrations.RemoveField(
            model_name='bankemployees',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='banks',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='hosts',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='processing',
            name='slug',
        ),
        migrations.AlterField(
            model_name='bankemployees',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bankemployees',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bankemployees',
            name='other',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bankemployees',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banks',
            name='address_eng',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banks',
            name='address_rus',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banks',
            name='full_name_eng',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banks',
            name='full_name_rus',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banks',
            name='host_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.hosts'),
        ),
        migrations.AlterField(
            model_name='banks',
            name='name_eng',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='banks',
            name='name_rus',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banks',
            name='processing_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.processing'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='name_eng',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='countries',
            name='name_rus',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='countries',
            name='short_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='payment_system',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='processing',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projectline',
            name='payment_system',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='KCVKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.banks')),
            ],
        ),
        migrations.CreateModel(
            name='EMV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField()),
                ('actual_date_time', models.DateTimeField()),
                ('chip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.chips')),
            ],
        ),
        migrations.AddField(
            model_name='chips',
            name='test_key_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.testkeys'),
        ),
        migrations.CreateModel(
            name='ChipDatasheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('chip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.chips')),
                ('datasheet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.datasheets')),
            ],
        ),
        migrations.CreateModel(
            name='BanksChips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.banks')),
                ('chip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.chips')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.statuses')),
            ],
        ),
    ]
