# Generated by Django 4.2 on 2023-05-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_cardscategories_chipcolor_effects_magstripecolor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChipColor',
            new_name='ChipColors',
        ),
    ]
