# Generated by Django 4.2 on 2023-05-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_rename_chipcolor_chipcolors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MagstripeColor',
            new_name='MagstripeColors',
        ),
        migrations.RenameModel(
            old_name='PlasticColor',
            new_name='PlasticColors',
        ),
        migrations.RenameModel(
            old_name='PlasticType',
            new_name='PlasticTypes',
        ),
    ]
