# Generated by Django 4.1.9 on 2023-05-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_rename_magstripecolor_magstripecolors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='bank_name_eng',
        ),
        migrations.RemoveField(
            model_name='projectline',
            name='bank_name_eng',
        ),
    ]
