# Generated by Django 4.1.9 on 2023-05-27 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0010_projectline_bank_name_eng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectline',
            name='bank_name_eng',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.banks'),
        ),
    ]
