# Generated by Django 4.1.9 on 2023-05-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0012_remove_projectline_bank_name_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectline',
            name='bank_name_eng',
            field=models.CharField(default=1, max_length=255, verbose_name='Название банка'),
            preserve_default=False,
        ),
    ]
