# Generated by Django 4.1.9 on 2023-05-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0015_projectline_bank_name_eng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectline',
            name='bank_name_eng',
        ),
    ]
