# Generated by Django 4.1.9 on 2023-05-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0022_alter_projectline_payment_system'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankName',
        ),
    ]
