# Generated by Django 4.1.9 on 2023-05-29 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0024_alter_projectline_card_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectline',
            name='chip_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.chips'),
        ),
    ]
