# Generated by Django 4.1.9 on 2023-05-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0025_alter_projectline_chip_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectline',
            name='chip_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название чипа'),
        ),
    ]
