# Generated by Django 4.1.9 on 2023-05-29 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0027_remove_projectline_chip_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectline',
            name='chip_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.chips'),
        ),
    ]
