# Generated by Django 4.1.9 on 2023-05-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0028_projectline_chip_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectline',
            name='chip_full_name',
        ),
    ]
