# Generated by Django 4.1.9 on 2023-05-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0030_alter_projectline_chip_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectline',
            name='chip_color',
        ),
        migrations.RemoveField(
            model_name='projectline',
            name='magstripe_color',
        ),
        migrations.RemoveField(
            model_name='projectline',
            name='plastic_color',
        ),
        migrations.RemoveField(
            model_name='projectline',
            name='plastic_type',
        ),
    ]
