# Generated by Django 4.1.9 on 2023-05-29 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0031_remove_projectline_chip_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectline',
            name='chip_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.chipcolors'),
        ),
        migrations.AddField(
            model_name='projectline',
            name='magstripe_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.magstripecolors'),
        ),
        migrations.AddField(
            model_name='projectline',
            name='plastic_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.plasticcolors'),
        ),
        migrations.AddField(
            model_name='projectline',
            name='plastic_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.plastictypes'),
        ),
    ]
