# Generated by Django 4.1.9 on 2023-05-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0032_projectline_chip_color_projectline_magstripe_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectline',
            name='card_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projectline',
            name='card_quality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
