# Generated by Django 4.1.9 on 2023-05-31 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0033_alter_projectline_card_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='address_eng',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banks',
            name='address_rus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banks',
            name='full_name_eng',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banks',
            name='full_name_rus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banks',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.hosts'),
        ),
        migrations.AlterField(
            model_name='banks',
            name='processing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.processing'),
        ),
        migrations.AlterField(
            model_name='banks',
            name='tolerance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
