# Generated by Django 4.1.9 on 2023-06-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0034_alter_banks_address_eng_alter_banks_address_rus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectline',
            name='magstr_color',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
