# Generated by Django 4.1.9 on 2023-06-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0036_remove_projectline_magstr_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectline',
            name='effects',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
