# Generated by Django 4.1.9 on 2023-06-05 07:15

import backend_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0038_inputpicfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputpicfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=backend_api.models),
        ),
    ]
