# Generated by Django 4.1.9 on 2023-06-05 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0040_alter_inputpicfiles_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputpicfiles',
            name='project_line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend_api.projectline'),
            preserve_default=False,
        ),
    ]
