# Generated by Django 4.1.9 on 2023-06-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0041_alter_inputpicfiles_project_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputpicfiles',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
