# Generated by Django 4.1.9 on 2023-06-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0043_alter_inputpicfiles_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputpicfiles',
            name='status',
            field=models.CharField(default='Активен', max_length=255),
        ),
    ]
