# Generated by Django 4.1.9 on 2023-06-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0046_inputpicfiles_delete_projectinputpicfiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InputPicFiles',
            new_name='ProjectInputPicFiles',
        ),
    ]
