# Generated by Django 4.1.9 on 2023-06-08 11:36

import backend_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0047_rename_inputpicfiles_projectinputpicfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinputpicfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=backend_api.models),
        ),
    ]
