# Generated by Django 4.1.9 on 2023-06-10 10:46

import backend_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0048_alter_projectinputpicfiles_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinesFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=backend_api.models)),
                ('name', models.CharField(max_length=255)),
                ('file_extension', models.CharField(max_length=255)),
                ('line_type', models.IntegerField()),
                ('process_step', models.IntegerField()),
                ('line_number', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Активен', max_length=255)),
            ],
        ),
    ]
