# Generated by Django 4.1.9 on 2023-06-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0049_linesfiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectInputPicFiles',
        ),
    ]
