# Generated by Django 4.1.9 on 2023-06-10 14:51

import backend_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0052_alter_linesfiles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linesfiles',
            name='file',
            field=models.FileField(upload_to=backend_api.models.LinesFiles.upload_LinesFiles),
        ),
    ]
