# Generated by Django 4.1.9 on 2023-06-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0053_alter_linesfiles_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectline',
            name='bank_name_eng',
        ),
        migrations.RemoveField(
            model_name='projectline',
            name='card_category',
        ),
        migrations.RemoveField(
            model_name='projectline',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='projectline',
            name='card_quality',
        ),
        migrations.RemoveField(
            model_name='projectline',
            name='chip_color',
        ),
        migrations.RemoveField(
            model_name='projectline',
            name='chip_name',
        ),
        migrations.RemoveField(
            model_name='projectline',
            name='effects',
        ),
        migrations.RemoveField(
            model_name='projectline',
            name='in_archive',
        ),
        migrations.RemoveField(
            model_name='projectline',
            name='magstripe_color',
        ),
        migrations.RemoveField(
            model_name='projectline',
            name='payment_system',
        ),
        migrations.RemoveField(
            model_name='projectline',
            name='plastic_color',
        ),
        migrations.RemoveField(
            model_name='projectline',
            name='plastic_type',
        ),
        migrations.RemoveField(
            model_name='projectline',
            name='put_date',
        ),
        migrations.RemoveField(
            model_name='projectline',
            name='slug',
        ),
    ]
