# Generated by Django 4.1.9 on 2023-06-11 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0054_remove_projectline_bank_name_eng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectline',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend_api.banks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectline',
            name='general_line_status',
            field=models.CharField(default='Проект', max_length=255),
        ),
        migrations.AddField(
            model_name='projectline',
            name='number',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectline',
            name='payment_system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend_api.paymentsystems'),
            preserve_default=False,
        ),
    ]
