# Generated by Django 4.1.9 on 2023-06-11 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0055_projectline_bank_projectline_general_line_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectline',
            name='card_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend_api.cardscategories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectline',
            name='card_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectline',
            name='card_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectline',
            name='card_revision',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
