# Generated by Django 4.1.9 on 2023-06-11 15:54

import backend_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0057_projectline_bank_communication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectline',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectline',
            name='in_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectline',
            name='modified_by_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectline',
            name='preview_image',
            field=models.FileField(blank=True, upload_to=backend_api.models.ProjectLine.upload_PreviewFiles),
        ),
    ]
