# Generated by Django 4.1.9 on 2023-06-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0058_projectline_created_by_name_projectline_in_archive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectline',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
