# Generated by Django 4.1.9 on 2023-06-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0059_projectline_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectline',
            name='modified_date',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
