# Generated by Django 4.1.9 on 2023-06-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0060_projectline_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectline',
            name='card_quality_fact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
