# Generated by Django 4.1.9 on 2023-06-11 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0061_alter_projectline_card_quality_fact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectline',
            name='bank_communication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectline',
            name='card_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectline',
            name='card_effects',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectline',
            name='card_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectline',
            name='card_revision',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectline',
            name='chip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.chips'),
        ),
        migrations.AlterField(
            model_name='projectline',
            name='chip_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.chipcolors'),
        ),
        migrations.AlterField(
            model_name='projectline',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectline',
            name='general_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectline',
            name='magstripe_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.magstripecolors'),
        ),
        migrations.AlterField(
            model_name='projectline',
            name='material_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.plasticcolors'),
        ),
        migrations.AlterField(
            model_name='projectline',
            name='material_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.plastictypes'),
        ),
        migrations.AlterField(
            model_name='projectline',
            name='modified_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectline',
            name='modified_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectline',
            name='number',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projectline',
            name='vendor_communication',
            field=models.TextField(blank=True, null=True),
        ),
    ]
