# Generated by Django 4.1.9 on 2023-06-12 06:00

import backend_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0063_rename_plasticcolors_materialcolors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectline',
            name='preview_image',
            field=models.FileField(blank=True, default='/Превью/Empty.png', upload_to=backend_api.models.ProjectLine.upload_PreviewFiles),
        ),
    ]
