# Generated by Django 4.1.9 on 2023-06-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0065_processlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='processlist',
            name='component_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processlist',
            name='position_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
