# Generated by Django 4.1.9 on 2023-06-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0067_remove_processlist_component_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessList',
        ),
    ]
