# Generated by Django 4.1.9 on 2023-06-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0069_processlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(max_length=255)),
                ('line_number', models.IntegerField()),
                ('process_step', models.CharField(max_length=255)),
                ('step_status', models.CharField(default='Wait', max_length=255)),
                ('modified_date', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('step_comment', models.TextField()),
            ],
        ),
    ]
