# Generated by Django 4.1.9 on 2023-06-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0070_processdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processdata',
            name='step_status',
            field=models.CharField(max_length=255),
        ),
    ]
