# Generated by Django 4.1.9 on 2023-06-16 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0071_alter_processdata_step_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processdata',
            name='modified_by_name',
        ),
        migrations.RemoveField(
            model_name='processdata',
            name='modified_date',
        ),
    ]
