# Generated by Django 4.1.9 on 2023-06-23 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0076_cardscategories_payment_system_chips_payment_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectline',
            name='bank_employee_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.bankemployees'),
        ),
    ]
