# Generated by Django 4.1.9 on 2023-06-23 15:31

import backend_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0078_rename_bank_employee_name_projectline_bank_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectline',
            name='preview_image',
            field=models.FileField(blank=True, default='/Превью/Empty.png', max_length=250, upload_to=backend_api.models.ProjectLine.upload_PreviewFiles),
        ),
    ]
