# Generated by Django 4.1.9 on 2023-06-26 11:19

import backend_api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0079_alter_projectline_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectline',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.banks'),
        ),
        migrations.AlterField(
            model_name='projectline',
            name='card_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.cardscategories'),
        ),
        migrations.AlterField(
            model_name='projectline',
            name='card_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectline',
            name='general_line_status',
            field=models.CharField(blank=True, default='Проект', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectline',
            name='payment_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.paymentsystems'),
        ),
        migrations.AlterField(
            model_name='projectline',
            name='preview_image',
            field=models.FileField(blank=True, default='/Превью/Empty.png', max_length=250, null=True, upload_to=backend_api.models.ProjectLine.upload_PreviewFiles),
        ),
    ]
